export const meta = {
  slug: 'boot-void',
  title: 'Boot Void',
  description:
    'A retro console boot homage co-driven by vgpu and TypeGPU on one shared device: TypeGPU simulates light-seeking dust with typed schemas, fed by the irradiance vgpu renders through radiance cascades, and vgpu draws the particle buffer back zero-copy. Plus a render bundle, bloom, and a CRT finish.',
  tags: [
    'instancing',
    'particles',
    'compute',
    'simulation',
    'bloom',
    'lighting',
    'raymarching',
    'post-processing',
    'render-bundles',
    'animation',
  ],
  capabilities: [
    'webgpu',
    'render-targets',
    'multi-pass',
    'instanced-rendering',
    'render-bundles',
    'controls',
    'select-control',
    'compute-shader',
    'storage-buffers',
    'gpu-buffer-interop',
    'zero-copy',
    'textures',
    'hdr',
    'pointer-input',
    'responsive-canvas',
    'continuous-rendering',
  ],
  thumb: { warmupFrames: 60, dt: 1 / 60, time: 2 },
  files: [
    'index.tsx',
    'renderer.ts',
    'pipeline.ts',
    'dust.ts',
    'dust-vgpu.ts',
    'dust-sim.wgsl',
    'radiance.ts',
    'nebula.wgsl',
    'stars.wgsl',
    'field.wgsl',
    'glass.wgsl',
    'atmosphere.wgsl',
    'trails.wgsl',
    'rc-emitter.wgsl',
    'rc-directions.wgsl',
    'sdf-sample.wgsl',
    'jfa-init.wgsl',
    'jfa-pass.wgsl',
    'sdf-finalize.wgsl',
    'radiance-cascade.wgsl',
    'rc-resolve.wgsl',
    'bright.wgsl',
    'blur.wgsl',
    'post.wgsl',
  ],
} as const;
